#define PROJECT_WIFI_SSID "RD-SEAI_2.4G"
#define PROJECT_WIFI_PASSWORD "ACLAB2024"

#define AIO_SERVER "io.adafruit.com"
#define AIO_SERVERPORT 1883
#define AIO_USERNAME "aclab241"
#define AIO_KEY "aio_ENtM49fWY0oZ6rC8BKgrROQIxgOg"